### PR TITLE
Change startTime to 2020-12-09T00:00:00Z for safe launch

### PR DESCRIPTION
**Pull request by fr-jerry-smith**
* '2020-12-06T00:00:00Z') / 1000 => '2020-12-09T00:00:00Z') / 1000
* getter method of lastAllocated state

### CODE REVIEW

**Review by valo — COMMENTED** [review]
LGTM

What about setting the `seigniorageSaved` in case there is BAC coming from the migration?

**Comment by fr-jerry-smith** [comment]
> LGTM
> 
> What about setting the `seigniorageSaved` in case there is BAC coming from the migration?

Thanks for your feedback, we're currently discussing this issue in Basiscash analysis group. Please send DM to @DeFiMorty for further discussion on TG group.

**Comment by slaking** [comment]
Can you guys please move to discord? Telegram requires a phone number and has much worse desktop apps.

**Comment by fr-jerry-smith** [comment]
Discord is now open guys :) 
@slaking

**Pull request merged**
